const formatET = value => new Intl.DateTimeFormat('en-US', {timeZone: 'America/New_York', dateStyle: 'medium', timeStyle: 'long'}).format(new Date(value));
let config, selectedRun;
const LEGACY_SEARCH_BUDGETS = new Set(['search_attempts', 'search_results']);
const SEARCH_POLICY_NOTICE = 'Search is adaptive and has no application limit on searches, total results, results per call, or tokens. Actual search activity is shown for information only (provider-native-unbounded).';
const BUDGET_HELP = {fetch_attempts: 'Maximum governed fetch units reserved across this run; default 5,000 units.', retries_per_item: 'Maximum retries for each acquisition item; default 2 retries per item.', runtime_seconds: 'Maximum cumulative acquisition runtime; default 3,600 seconds.'};
const $ = selector => document.querySelector(selector);
async function refreshPipeline() { $('#pipeline-detail').textContent = JSON.stringify(await api('/api/manage/pipeline'), null, 2); }
document.addEventListener('DOMContentLoaded', () => { $('#refresh-pipeline').onclick = () => refreshPipeline().catch(error => $('#pipeline-detail').textContent = error.message); });
const clear = node => { node.replaceChildren(); return node; };
const text = (tag, value, className) => { const node = document.createElement(tag); node.textContent = String(value); if (className) node.className = className; return node; };
const labeledInput = (label, name, value, attributes = {}) => { const wrapper = text('label', label); const input = document.createElement('input'); input.name = name; input.value = String(value ?? ''); Object.assign(input, attributes); wrapper.append(input); return wrapper; };
async function api(url, options = {}) { const response = await fetch(url, {...options, headers: {'content-type': 'application/json', ...(options.headers || {})}}); if (response.status === 401) { location.href = '/manage/login?next=' + encodeURIComponent(location.pathname + location.search); throw Error('session expired'); } if (!response.ok) { let detail; try { detail = (await response.json()).detail; } catch { detail = await response.text(); } throw Error(detail || response.statusText); } return response.status === 204 ? null : response.json(); }
const visiblePreview = value => { const view = structuredClone(value); for (const branch of [view.definition, view.effective]) { const budgets = branch?.parameters?.budgets; if (!budgets) continue; for (const key of LEGACY_SEARCH_BUDGETS) delete budgets[key]; } return view; };
function definition() { const form = new FormData($('#parameters')), value = structuredClone(config.definition), mode = form.get('date_mode'); Object.assign(value.parameters, {report_date: form.get('report_date'), timezone: form.get('timezone'), source_keys: String(form.get('source_keys')).split(',').map(x => x.trim()).filter(Boolean), provider: form.get('provider'), model: form.get('model')}); value.parameters.date_policy = mode === 'unlimited' ? {mode} : mode === 'recent' ? {mode, days: Number(form.get('days'))} : {mode, start: form.get('start'), end: form.get('end')}; for (const input of $('#budgets').querySelectorAll('input[name^="budget_"]')) value.parameters.budgets[input.name.slice(7)] = Number(form.get(input.name)); for (const [name, prompt] of Object.entries(value.prompts)) { prompt.version = $(`[name="prompt_version_${name}"]`).value; prompt.text = $(`[name="prompt_${name}"]`).value; } value.meeting = {enabled: $('[name="meeting_enabled"]').checked, prompt: {version: $('[name="meeting_prompt_version"]').value, text: $('[name="meeting_prompt"]').value}}; return value; }
function renderConfig() { const parameters = config.definition.parameters, form = $('#parameters'); for (const name of ['report_date', 'timezone', 'provider', 'model']) form.elements[name].value = parameters[name]; form.elements.source_keys.value = parameters.source_keys.join(', '); form.elements.date_mode.value = parameters.date_policy.mode; form.elements.days.value = parameters.date_policy.days || ''; form.elements.start.value = parameters.date_policy.start || ''; form.elements.end.value = parameters.date_policy.end || ''; const budgets = clear($('#budgets')); for (const [key, value] of Object.entries(parameters.budgets)) { if (LEGACY_SEARCH_BUDGETS.has(key)) continue; const input = labeledInput(key.replaceAll('_', ' '), 'budget_' + key, value, {type: 'number', min: '0'}); input.append(text('small', BUDGET_HELP[key] || 'Maximum allowed value for this run; see the task reference for this budget.')); budgets.append(input); } budgets.append(text('p', SEARCH_POLICY_NOTICE)); const prompts = clear($('#prompts')); prompts.append(text('h2', 'Five business prompt components'), text('p', 'Edit version labels and instruction text. Changes are saved as a new configuration version and apply to new bindings.')); for (const [name, value] of Object.entries(config.definition.prompts)) { const article = document.createElement('article'); article.append(text('h3', name.replaceAll('_', ' ')), labeledInput('Component version', 'prompt_version_' + name, value.version)); const versionNote = text('small', 'Version label recorded with this prompt and frozen for new runs.'); article.lastChild.append(versionNote); const label = text('label', 'Prompt text'), area = document.createElement('textarea'); area.name = 'prompt_' + name; area.value = value.text; label.append(area, text('small', 'Instructions for this business step; changing them does not rewrite prompts already frozen into runs.')); article.append(label, text('code', `SHA-256 ${config.hashes.components[name]}`)); prompts.append(article); } $('[name="meeting_enabled"]').checked = config.definition.meeting.enabled; $('[name="meeting_prompt_version"]').value = config.definition.meeting.prompt.version; $('[name="meeting_prompt"]').value = config.definition.meeting.prompt.text; $('#meeting-hash').textContent = `SHA-256 ${config.hashes.meeting}`; $('#version').textContent = `Task version ${config.version}`; $('#effective').textContent = JSON.stringify(visiblePreview({effective: config.effective, effective_meeting: config.effective_meeting, resolved_date_range: config.resolved_date_range, hashes: config.hashes}), null, 2); }
async function showDiff() { const version = Number($('#versions').value); $('#version-diff').textContent = version === config.version ? 'Selected version is active (no diff).' : JSON.stringify(await api(`/api/manage/diff?old_version=${version}&new_version=${config.version}`), null, 2); }
async function load() { config = await api('/api/manage/config'); renderConfig(); const versions = clear($('#versions')); for (const value of await api('/api/manage/versions')) { const option = document.createElement('option'); option.value = String(value.version); option.textContent = `v${value.version} · ${formatET(value.saved_at)}${value.active ? ' · active' : ''}`; versions.append(option); } versions.onchange = () => showDiff().catch(error => $('#message').textContent = error.message); await showDiff(); }
async function preview() { const value = await api('/api/manage/config/preview', {method: 'POST', body: JSON.stringify(definition())}); $('#effective').textContent = JSON.stringify(visiblePreview(value), null, 2); $('#message').textContent = 'Valid configuration preview; nothing saved.'; }
async function save() { config = await api(`/api/manage/config?expected_version=${config.version}`, {method: 'PUT', body: JSON.stringify(definition())}); $('#message').textContent = `Saved version ${config.version}. Existing runs remain frozen.`; await load(); }
async function restore() { const version = $('#versions').value; config = await api(`/api/manage/versions/${version}/restore?expected_version=${config.version}`, {method: 'POST'}); $('#message').textContent = `Restored v${version} as new version ${config.version}.`; await load(); }
async function runs() { const rows = await api('/api/manage/progress'), list = clear($('#run-list')); if (!rows.length) list.append(document.createTextNode('No runs yet.')); for (const value of rows) { const button = text('button', `${value.run_id}\n${value.stage} · ${value.freshness}`, 'run'); button.dataset.id = value.run_id; button.onclick = () => selectRun(button.dataset.id); list.append(button); } }
function showMeetingError(error) { $('#meeting-progress').textContent = JSON.stringify({status: 'error', error: error?.message || String(error)}, null, 2); }
async function selectRun(id) { try { selectedRun = id; document.querySelectorAll('.run').forEach(button => button.classList.toggle('active', button.dataset.id === id)); const [value, meetings] = await Promise.all([api(`/api/manage/runs/${encodeURIComponent(id)}/progress`), api(`/api/manage/runs/${encodeURIComponent(id)}/meetings`)]); $('#run-detail').textContent = (value.stage === 'completed_with_gaps' ? 'Acquisition completed with gaps. Report and publication remain blocked.\n\n' : '') + JSON.stringify({...value, items: undefined}, null, 2); $('#meeting-progress').textContent = JSON.stringify(meetings, null, 2); $('#resume').disabled = false; $('#start-meetings').disabled = false; $('#retry-meetings').disabled = false; const items = clear($('#items')); if (!value.items.length) items.append(document.createTextNode('No stored items yet.')); for (const item of value.items) { const button = text('button', `${item.organization || 'unknown'} · ${item.title || item.url}\n${item.status || 'unknown'} · ${item.eligibility || 'unknown date eligibility'}`, 'item'); button.onclick = async () => { $('#item-detail').textContent = JSON.stringify(await api(`/api/manage/runs/${encodeURIComponent(id)}/items/${encodeURIComponent(item.item_id)}`), null, 2); }; items.append(button); } } catch (error) { for (const id of ['start-meetings', 'retry-meetings']) $('#' + id).disabled = true; showMeetingError(error); } }
async function processMeetings(retryFailed) { try { await api(`/api/manage/runs/${encodeURIComponent(selectedRun)}/meetings`, {method: 'POST', body: JSON.stringify({retry_failed: retryFailed})}); await selectRun(selectedRun); } catch (error) { showMeetingError(error); } }
async function queryMeetings() { const form = new FormData($('#meeting-filters')), query = new URLSearchParams(); for (const name of ['organizer', 'event_types', 'start_date', 'end_date', 'base_date', 'timezone_name']) if (form.get(name)) query.set(name, form.get(name)); for (const name of ['include_unknown', 'include_deadlines', 'include_cancelled', 'include_retrospective']) query.set(name, String(form.has(name))); $('#meeting-list').textContent = JSON.stringify(await api('/api/manage/meetings?' + query), null, 2); }
async function refreshChatTokens() {
  const rows = await api('/api/manage/chat-tokens');
  const list = clear($('#chat-token-list'));
  for (const item of rows) {
    const row = document.createElement('tr');
    for (const value of [item.label, formatET(item.created_at), item.status]) row.append(text('td', value));
    const action = document.createElement('td');
    if (item.status === 'active') {
      const button = text('button', 'Revoke');
      button.type = 'button';
      button.onclick = async () => {
        try {
          await api(`/api/manage/chat-tokens/${encodeURIComponent(item.id)}`, {method: 'DELETE'});
          $('#chat-token-secret').textContent = '';
          await refreshChatTokens();
        } catch (error) { $('#chat-token-message').textContent = error.message; }
      };
      action.append(button);
    }
    row.append(action);
    list.append(row);
  }
}
$('#create-chat-token').onsubmit = async event => {
  event.preventDefault();
  const button = event.currentTarget.querySelector('button');
  button.disabled = true;
  $('#chat-token-secret').textContent = '';
  try {
    const item = await api('/api/manage/chat-tokens', {method: 'POST', body: JSON.stringify({label: $('#chat-token-label').value.trim()})});
    $('#chat-token-secret').textContent = item.token;
    $('#chat-token-message').textContent = 'Copy this token now. Its secret will not be shown again.';
    $('#chat-token-label').value = '';
    await refreshChatTokens();
  } catch (error) { $('#chat-token-message').textContent = error.message; }
  finally { button.disabled = false; }
};
$('#refresh-chat-tokens').onclick = () => refreshChatTokens().catch(error => $('#chat-token-message').textContent = error.message);
const tabs = [...document.querySelectorAll('[role="tab"][data-tab]')];
function tabFromLocation() { if (location.pathname === '/manage/pdf-import') return 'pdf-import'; const requested = new URLSearchParams(location.search).get('tab'); return tabs.some(tab => tab.dataset.tab === requested && requested !== 'pdf-import') ? requested : 'configuration'; }
function tabPath(name) { return name === 'pdf-import' ? '/manage/pdf-import' : name === 'configuration' ? '/manage' : `/manage?tab=${name}`; }
function selectTab(name, push = false) { const selected = tabs.find(tab => tab.dataset.tab === name) || tabs[0]; tabs.forEach(tab => { const active = tab === selected; tab.classList.toggle('active', active); tab.setAttribute('aria-selected', String(active)); tab.tabIndex = active ? 0 : -1; }); document.querySelectorAll('[role="tabpanel"]').forEach(panel => { panel.hidden = panel.id !== selected.getAttribute('aria-controls'); }); const path = tabPath(selected.dataset.tab); if (push && location.pathname + location.search !== path) history.pushState(null, '', path); if (selected.dataset.tab === 'runs') runs().catch(error => $('#message').textContent = error.message); if (selected.dataset.tab === 'meetings') queryMeetings().catch(error => $('#message').textContent = error.message); if (selected.dataset.tab === 'chat-tokens') refreshChatTokens().catch(error => $('#chat-token-message').textContent = error.message); if (selected.dataset.tab === 'pdf-import') window.refreshPdfImportOverview?.(); }
tabs.forEach((tab, index) => { tab.onclick = () => selectTab(tab.dataset.tab, true); tab.onkeydown = event => { const next = event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index + tabs.length - 1) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : null; if (next === null) return; event.preventDefault(); tabs[next].focus(); selectTab(tabs[next].dataset.tab, true); }; });
window.addEventListener('popstate', () => selectTab(tabFromLocation()));
selectTab(tabFromLocation());
async function start(mode) { const value = await api('/api/manage/runs', {method: 'POST', body: JSON.stringify({mode})}); await runs(); await selectRun(value.run_id); }
$('#preview').onclick = () => preview().catch(error => $('#message').textContent = error.message); $('#save').onclick = () => save().catch(error => $('#message').textContent = error.message); $('#restore').onclick = () => restore().catch(error => $('#message').textContent = error.message); $('#start').onclick = () => start('report'); $('#start-ingest').onclick = () => start('ingest_only'); $('#refresh').onclick = () => runs().catch(error => $('#message').textContent = error.message); $('#resume').onclick = async () => { await api(`/api/manage/runs/${encodeURIComponent(selectedRun)}/resume`, {method: 'POST'}); await selectRun(selectedRun); }; $('#start-meetings').onclick = () => processMeetings(false); $('#retry-meetings').onclick = () => processMeetings(true); $('#meeting-filters').onsubmit = event => { event.preventDefault(); queryMeetings().catch(error => $('#message').textContent = error.message); }; $('#logout').onclick = async () => { await api('/api/manage/auth/logout', {method: 'POST'}); location.href = '/manage/login?next=' + encodeURIComponent(location.pathname + location.search); }; load().catch(error => $('#message').textContent = error.message);
