let config, selectedRun;
const $ = selector => document.querySelector(selector);
const clear = node => { node.replaceChildren(); return node; };
const text = (tag, value, className) => { const node = document.createElement(tag); node.textContent = String(value); if (className) node.className = className; return node; };
const labeledInput = (label, name, value, attributes = {}) => { const wrapper = text('label', label); const input = document.createElement('input'); input.name = name; input.value = String(value ?? ''); Object.assign(input, attributes); wrapper.append(input); return wrapper; };
async function api(url, options = {}) { const response = await fetch(url, {...options, headers: {'content-type': 'application/json', ...(options.headers || {})}}); if (response.status === 401) { location.href = '/manage/login'; throw Error('session expired'); } if (!response.ok) { let detail; try { detail = (await response.json()).detail; } catch { detail = await response.text(); } throw Error(detail || response.statusText); } return response.status === 204 ? null : response.json(); }
function definition() { const form = new FormData($('#parameters')), value = structuredClone(config.definition), mode = form.get('date_mode'); Object.assign(value.parameters, {report_date: form.get('report_date'), timezone: form.get('timezone'), source_keys: String(form.get('source_keys')).split(',').map(x => x.trim()).filter(Boolean), provider: form.get('provider'), model: form.get('model')}); value.parameters.date_policy = mode === 'unlimited' ? {mode} : mode === 'recent' ? {mode, days: Number(form.get('days'))} : {mode, start: form.get('start'), end: form.get('end')}; for (const key of Object.keys(value.parameters.budgets)) value.parameters.budgets[key] = Number(form.get('budget_' + key)); for (const [name, prompt] of Object.entries(value.prompts)) { prompt.version = $(`[name="prompt_version_${name}"]`).value; prompt.text = $(`[name="prompt_${name}"]`).value; } return value; }
function renderConfig() { const parameters = config.definition.parameters, form = $('#parameters'); for (const name of ['report_date', 'timezone', 'provider', 'model']) form.elements[name].value = parameters[name]; form.elements.source_keys.value = parameters.source_keys.join(', '); form.elements.date_mode.value = parameters.date_policy.mode; form.elements.days.value = parameters.date_policy.days || ''; form.elements.start.value = parameters.date_policy.start || ''; form.elements.end.value = parameters.date_policy.end || ''; const budgets = clear($('#budgets')); for (const [key, value] of Object.entries(parameters.budgets)) budgets.append(labeledInput(key.replaceAll('_', ' '), 'budget_' + key, value, {type: 'number', min: '0'})); const prompts = clear($('#prompts')); prompts.append(text('h2', 'Five business prompt components')); for (const [name, value] of Object.entries(config.definition.prompts)) { const article = document.createElement('article'); article.append(text('h3', name.replaceAll('_', ' ')), labeledInput('Component version', 'prompt_version_' + name, value.version)); const label = text('label', 'Prompt text'), area = document.createElement('textarea'); area.name = 'prompt_' + name; area.value = value.text; label.append(area); article.append(label, text('code', `SHA-256 ${config.hashes.components[name]}`)); prompts.append(article); } $('#version').textContent = `Task version ${config.version}`; $('#effective').textContent = JSON.stringify({effective: config.effective, resolved_date_range: config.resolved_date_range, hashes: config.hashes}, null, 2); }
async function showDiff() { const version = Number($('#versions').value); $('#version-diff').textContent = version === config.version ? 'Selected version is active (no diff).' : JSON.stringify(await api(`/api/manage/diff?old_version=${version}&new_version=${config.version}`), null, 2); }
async function load() { config = await api('/api/manage/config'); renderConfig(); const versions = clear($('#versions')); for (const value of await api('/api/manage/versions')) { const option = document.createElement('option'); option.value = String(value.version); option.textContent = `v${value.version} · ${value.saved_at}${value.active ? ' · active' : ''}`; versions.append(option); } versions.onchange = () => showDiff().catch(error => $('#message').textContent = error.message); await showDiff(); }
async function preview() { const value = await api('/api/manage/config/preview', {method: 'POST', body: JSON.stringify(definition())}); $('#effective').textContent = JSON.stringify(value, null, 2); $('#message').textContent = 'Valid configuration preview; nothing saved.'; }
async function save() { config = await api(`/api/manage/config?expected_version=${config.version}`, {method: 'PUT', body: JSON.stringify(definition())}); $('#message').textContent = `Saved version ${config.version}. Existing runs remain frozen.`; await load(); }
async function restore() { const version = $('#versions').value; config = await api(`/api/manage/versions/${version}/restore?expected_version=${config.version}`, {method: 'POST'}); $('#message').textContent = `Restored v${version} as new version ${config.version}.`; await load(); }
async function runs() { const rows = await api('/api/manage/progress'), list = clear($('#run-list')); if (!rows.length) list.append(document.createTextNode('No runs yet.')); for (const value of rows) { const button = text('button', `${value.run_id}\n${value.stage} · ${value.freshness}`, 'run'); button.dataset.id = value.run_id; button.onclick = () => selectRun(button.dataset.id); list.append(button); } }
async function selectRun(id) { selectedRun = id; document.querySelectorAll('.run').forEach(button => button.classList.toggle('active', button.dataset.id === id)); const value = await api(`/api/manage/runs/${encodeURIComponent(id)}/progress`); $('#run-detail').textContent = (value.stage === 'completed_with_gaps' ? 'Acquisition completed with gaps. Report and publication remain blocked.\n\n' : '') + JSON.stringify({...value, items: undefined}, null, 2); $('#resume').disabled = false; const items = clear($('#items')); if (!value.items.length) items.append(document.createTextNode('No stored items yet.')); for (const item of value.items) { const button = text('button', `${item.organization || 'unknown'} · ${item.title || item.url}\n${item.status || 'unknown'} · ${item.eligibility || 'unknown date eligibility'}`, 'item'); button.onclick = async () => { $('#item-detail').textContent = JSON.stringify(await api(`/api/manage/runs/${encodeURIComponent(id)}/items/${encodeURIComponent(item.item_id)}`), null, 2); }; items.append(button); } }
document.querySelectorAll('nav button').forEach(button => button.onclick = () => { document.querySelectorAll('nav button').forEach(other => other.classList.toggle('active', other === button)); for (const id of ['configuration', 'runs']) $('#' + id).hidden = id !== button.dataset.tab; if (button.dataset.tab === 'runs') runs().catch(error => $('#message').textContent = error.message); });
$('#preview').onclick = () => preview().catch(error => $('#message').textContent = error.message); $('#save').onclick = () => save().catch(error => $('#message').textContent = error.message); $('#restore').onclick = () => restore().catch(error => $('#message').textContent = error.message); $('#start').onclick = async () => { const value = await api('/api/manage/runs', {method: 'POST', body: '{}'}); await runs(); await selectRun(value.run_id); }; $('#refresh').onclick = () => runs().catch(error => $('#message').textContent = error.message); $('#resume').onclick = async () => { await api(`/api/manage/runs/${encodeURIComponent(selectedRun)}/resume`, {method: 'POST'}); await selectRun(selectedRun); }; $('#logout').onclick = async () => { await api('/api/manage/auth/logout', {method: 'POST'}); location.href = '/manage/login'; }; load().catch(error => $('#message').textContent = error.message);
